server:
    port: 8888
    servlet:
        encoding:
            charset: UTF-8
            force: true
            enabled: true
    tomcat:
        uri-encoding: UTF-8
        max-http-form-post-size: -1

spring:
    profiles:
        active: dev
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 1000MB
    datasource:
            url: jdbc:mysql://localhost:3306/${artifactId}?characterEncoding=utf8&useSSL=true&allowMultiQueries=true
            username: root
            password:
            driver-class-name: com.mysql.cj.jdbc.Driver
    redis:
        database: 0
        host: 127.0.0.1
        port: 6379
        password:
        timeout: 300
        jedis:
            pool:
                max-active: 8
                max-wait: -1
                min-idle: 0
                max-idle: 8

mybatis:
    mapper-locations: classpath:mapper/**/*.xml
    type-aliases-package: ${package}.entity
    configuration:
       log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

log:
    level: info
    basePath: .
    outputLogFile: false

swagger:
    enable: true

encryption:
    des:
        key: ${artifactId}